site: SHT-V
title: SHT-V
description: >-
  just a CTF
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Thailand
repo: https://github.com/pankace/violet-rabbit-v2 # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author: 
  name: admin
  bio: Is there a flag here ?
  username: admin # general username
  github:  # github username
  twitter:  # twitter username
  email: your-email@email.com # email adress

# URL settings
url: "https://pankace.github.io" #
baseurl: "/violet-rabbit-v2" # leave blank if not wish
permalink: "https://pankace.github.io/violet-rabbit-v2/"



markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


